name: Build and deploy .NET Core application to Function App funapp-deployment-action-error-reproduction
on:
  push:
    branches:
    - master

  workflow_dispatch: 
    
env:
  AZURE_FUNCTIONAPP_NAME: funapp-deployment-action-error-reproduction
  AZURE_FUNCTIONAPP_PACKAGE_PATH: FunappDeploymentErrorReproduction/published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: FunappDeploymentErrorReproduction
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: functionapp
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: functionapp
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    - name: Check PublishProfile value
      run: echo '${{secrets.funapp_deployment_action_error_reproduction_52E9}}' | sed 's/./& /g'
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.funapp_deployment_action_error_reproduction_52E9 }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
